package com.apartech.common.Constants;

/**
 * @author Jatin
 *
 * Copyright (C) 2006  Apartech Ltd. Jatin Bhadra

 */
public class JMXAdminConfig {


		public static final String ServerCluster ="ServerCluster";
		public static final String ApplicationServer = "ApplicationServer";
		public static final String JDBCProvider = "JDBCProvider";

/**public static final String AdminConfigObjectMessageQOP = "MessageQOP";
public static final String AdminConfigObjectProperty
public static final String AdminConfigObjectStreamRedirect
public static final String AdminConfigObjectMQQueueConnectionFactory
public static final String AdminConfigObjectApplication
public static final String AdminConfigObjectJDBCProvider
public static final String AdminConfigObjectMultibrokerDomain
public static final String AdminConfigObjectOutputRedirect
public static final String AdminConfigObjectTransportLayer
public static final String AdminConfigObjectMQQueue
public static final String AdminConfigObjectCustomService
public static final String AdminConfigObjectMultiBrokerRoutingEntry
public static final String AdminConfigObjectURLProvider
public static final String AdminConfigObjectJ2EEResourceFactory
public static final String AdminConfigObjectSecurity
public static final String AdminConfigObjectDeploymentTargetMapping
public static final String AdminConfigObjectVariableSubstitutionEntry
public static final String AdminConfigObjectEJBModuleDeployment
public static final String AdminConfigObjectMailSession
public static final String AdminConfigObjectEveryoneExt
public static final String AdminConfigObjectNamingContext
public static final String AdminConfigObjectRMIConnector
public static final String AdminConfigObjectVariableMap
public static final String AdminConfigObjectCell
public static final String AdminConfigObjectProcessExecution
public static final String AdminConfigObjectWebModuleDeployment
public static final String AdminConfigObjectDeployment
public static final String AdminConfigObjectCustomUserRegistry
public static final String AdminConfigObjectNameBinding
public static final String AdminConfigObjectSystemMessageServer
public static final String AdminConfigObjectForeignCell
public static final String AdminConfigObjectInstancePool
public static final String AdminConfigObjectIdentityAssertionTypeAssociation
public static final String AdminConfigObjectModuleConfig
public static final String AdminConfigObjectGenericJMSDestination
public static final String AdminConfigObjectMQTopicConnectionFactory
public static final String AdminConfigObjectModuleRef
public static final String AdminConfigObjectSSLConfig
public static final String AdminConfigObjectNodeAgent
public static final String AdminConfigObjectApplicationConfig
public static final String AdminConfigObjectAuthorizationTableExt
public static final String AdminConfigObjectStateManageable
public static final String AdminConfigObjectAllAuthenticatedUsersExt
public static final String AdminConfigObjectServerEntry
public static final String AdminConfigObjectApplicationManagementService
public static final String AdminConfigObjectDebugService
public static final String AdminConfigObjectTransactionService
public static final String AdminConfigObjectEjbNameSpaceBinding
public static final String AdminConfigObjectEndPointRef
public static final String AdminConfigObjectLocalOSUserRegistry
public static final String AdminConfigObjectSecurityProtocolConfig
public static final String AdminConfigObjectSecurityServer
public static final String AdminConfigObjectDataReplication
public static final String AdminConfigObjectSubjectExt
public static final String AdminConfigObjectRASLoggingService
public static final String AdminConfigObjectResourceEnvEntry
public static final String AdminConfigObjectAuthorizationConfig
public static final String AdminConfigObjectDynamicCache
public static final String AdminConfigObjectWebContainer
public static final String AdminConfigObjectSpecialSubjectExt
public static final String AdminConfigObjectWASTopicConnectionFactory
public static final String AdminConfigObjectHostAlias
public static final String AdminConfigObjectWASTopic
public static final String AdminConfigObjectDeployedObjectConfig
public static final String AdminConfigObjectDRSSerialization
public static final String AdminConfigObjectSecurityRoleExt
public static final String AdminConfigObjectRoleBasedAuthorization
public static final String AdminConfigObjectTuningParams
public static final String AdminConfigObjectWebModuleConfig
public static final String AdminConfigObjectPMIService
public static final String AdminConfigObjectCORBAObjectNameSpaceBinding
public static final String AdminConfigObjectTransportQOP
public static final String AdminConfigObjectThreadPool
public static final String AdminConfigObjectCryptoHardwareToken
public static final String AdminConfigObjectNode
public static final String AdminConfigObjectAuthenticationTarget
public static final String AdminConfigObjectPMIRequestMetrics
public static final String AdminConfigObjectObjectRequestBroker
public static final String AdminConfigObjectTAInterceptor
public static final String AdminConfigObjectSWAMAuthentication
public static final String AdminConfigObjectExtensionMBeanProvider
public static final String AdminConfigObjectRepositoryService
public static final String AdminConfigObjectServerTarget
public static final String AdminConfigObjectWASQueue
public static final String AdminConfigObjectApplicationContainer
public static final String AdminConfigObjectPMIRMFilter
public static final String AdminConfigObjectProcessDef
public static final String AdminConfigObjectRoleAssignmentExt
public static final String AdminConfigObjectTraceLog
public static final String AdminConfigObjectCookie
public static final String AdminConfigObjectComponent
public static final String AdminConfigObjectSecurityProtocolQOP
public static final String AdminConfigObjectCommonSecureInterop
public static final String AdminConfigObjectResourceEnvironmentProvider
public static final String AdminConfigObjectApplicationServer
public static final String AdminConfigObjectModuleShare
public static final String AdminConfigObjectPropertySet
public static final String AdminConfigObjectWAS40ConnectionPool
public static final String AdminConfigObjectResourceAdapter
public static final String AdminConfigObjectApplicationDeployment
public static final String AdminConfigObjectNameSpaceBinding
public static final String AdminConfigObjectCellManager
public static final String AdminConfigObjectAgent
public static final String AdminConfigObjectEnterpriseBeanConfig
public static final String AdminConfigObjectManagedObject
public static final String AdminConfigObjectConfigSynchronizationService
public static final String AdminConfigObjectServerIndex
public static final String AdminConfigObjectJ2EEResourcePropertySet
public static final String AdminConfigObjectPMIRMFilterValue
public static final String AdminConfigObjectMappingModule
public static final String AdminConfigObjectSecurityPermission
public static final String AdminConfigObjectKey
public static final String AdminConfigObjectExtensionMBean
public static final String AdminConfigObjectGenericJMSConnectionFactory
public static final String AdminConfigObjectConnector
public static final String AdminConfigObjectReferenceable
public static final String AdminConfigObjectSecureAssociationService
public static final String AdminConfigObjectAuthMechanism
public static final String AdminConfigObjectService
public static final String AdminConfigObjectMailProvider
public static final String AdminConfigObjectServiceContext
public static final String AdminConfigObjectJAASLoginModule
public static final String AdminConfigObjectHTTPConnector
public static final String AdminConfigObjectTaskProvider
public static final String AdminConfigObjectLicense
public static final String AdminConfigObjectURL
public static final String AdminConfigObjectInterceptor
public static final String AdminConfigObjectEJBContainer
public static final String AdminConfigObjectConnectionFactory
public static final String AdminConfigObjectListenerPort
public static final String AdminConfigObjectClassloader
public static final String AdminConfigObjectIdentityAssertionLayer
public static final String AdminConfigObjectConfigProperty
public static final String AdminConfigObjectSessionManager
public static final String AdminConfigObjectMessageListenerService
public static final String AdminConfigObjectIdentityAssertionQOP
public static final String AdminConfigObjectEndPoint
public static final String AdminConfigObjectCustomAuthMechanism
public static final String AdminConfigObjectIndirectLookupNameSpaceBinding
public static final String AdminConfigObjectTypedProperty
public static final String AdminConfigObjectHTTPTransport
public static final String AdminConfigObjectJMXConnector
public static final String AdminConfigObjectEJBCache
public static final String AdminConfigObjectIIOPSecurityProtocol
public static final String AdminConfigObjectProtocolProvider
public static final String AdminConfigObjectLTPA
public static final String AdminConfigObjectExternalCacheGroup
public static final String AdminConfigObjectSingleSignon
public static final String AdminConfigObjectTrustAssociation
public static final String AdminConfigObjectStatisticsProvider
public static final String AdminConfigObjectDRSPartition
public static final String AdminConfigObjectJ2EEResourceProvider
public static final String AdminConfigObjectDeployedObject
public static final String AdminConfigObjectExtension
public static final String AdminConfigObjectJAASConfigurationEntry
public static final String AdminConfigObjectTraceService
public static final String AdminConfigObjectJavaProcessDef
public static final String AdminConfigObjectSessionBeanConfig
public static final String AdminConfigObjectUserRegistry
public static final String AdminConfigObjectMonitoringPolicy
public static final String AdminConfigObjectExternallyManagedHTTPServer
public static final String AdminConfigObjectServerComponent
public static final String AdminConfigObjectJ2CConnectionFactory
public static final String AdminConfigObjectDeploymentTarget
public static final String AdminConfigObjectJ2CResourceAdapter
public static final String AdminConfigObjectBackupCluster
public static final String AdminConfigObjectDRSSettings
public static final String AdminConfigObjectServerCluster
public static final String AdminConfigObjectJ2EEResourceProperty
public static final String AdminConfigObjectConnectorModuleDeployment
public static final String AdminConfigObjectServerIdentity
public static final String AdminConfigObjectModuleDeployment
public static final String AdminConfigObjectNameServer
public static final String AdminConfigObjectWAS40DataSource
public static final String AdminConfigObjectEJBModuleConfiguration
public static final String AdminConfigObjectGroupExt
public static final String AdminConfigObjectWASQueueConnectionFactory
public static final String AdminConfigObjectIIOPLayer
public static final String AdminConfigObjectLibraryRef
public static final String AdminConfigObjectFileTransferService
public static final String AdminConfigObjectLDAPUserRegistry
public static final String AdminConfigObjectConnectionPool
public static final String AdminConfigObjectJMSConnector
public static final String AdminConfigObjectDRSConnectionPool
public static final String AdminConfigObjectJavaVirtualMachine
public static final String AdminConfigObjectJMSConnectionFactory
public static final String AdminConfigObjectORBPlugin
public static final String AdminConfigObjectClusterMember
public static final String AdminConfigObjectSecureSocketLayer
public static final String AdminConfigObjectAuthenticationMechanism
public static final String AdminConfigObjectMimeEntry
public static final String AdminConfigObjectTransport
public static final String AdminConfigObjectClusteredTarget
public static final String AdminConfigObjectIIOPTransport
public static final String AdminConfigObjectExternalCacheGroupMember
public static final String AdminConfigObjectSessionDatabasePersistence
public static final String AdminConfigObjectJMSDestination
public static final String AdminConfigObjectLibrary
public static final String AdminConfigObjectNamedEndPoint
public static final String AdminConfigObjectAuthorizationTableImpl
public static final String AdminConfigObjectQualityOfProtection
public static final String AdminConfigObjectJMSTransport
public static final String AdminConfigObjectDataSource

public static final String AdminConfigObjectJMSProvider
public static final String AdminConfigObjectAdminService
public static final String AdminConfigObjectUserExt
public static final String AdminConfigObjectWorkloadManagementServer
public static final String AdminConfigObjectStringNameSpaceBinding
public static final String AdminConfigObjectInvalidationSchedule
public static final String AdminConfigObjectServiceLog
public static final String AdminConfigObjectJMSServer
public static final String AdminConfigObjectServerExt
public static final String AdminConfigObjectJAASConfiguration
public static final String AdminConfigObjectVirtualHost
public static final String AdminConfigObjectStatefulSessionBeanConfig
public static final String AdminConfigObjectCMPConnectorFactory
public static final String AdminConfigObjectLSDConnection
public static final String AdminConfigObjectJAASAuthData
public static final String AdminConfigObjectServer
public static final String AdminConfigObjectAuthorizationProvider
public static final String AdminConfigObjectLDAPSearchFilter
public static final String AdminConfigObjectMQTopic
public static final String AdminConfigObjectMessageLayer
public static final String AdminConfigObjectSOAPConnector		**/


}
